export {default as cubetaAproil} from "./cubeta-tambo-aproil.webp"
export {default as tamborLine} from "./solo-linea.webp"
export {default as catalogMockup} from "./catalogo-mockup.webp"
export {default as lineaLarga} from "./linea-difuminado.svg"
export {default as pdfIcon} from "./pdf-aproil.svg"